version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: prisma_postgres
    restart: always
    environment:
      POSTGRES_USER: leetcode_user
      POSTGRES_PASSWORD: leetcode_password
      POSTGRES_DB: leetcode_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
